### ISSUE TITLE
Windows install failure

### ISSUE THREAD

**Issue by mihaidma** [nearform/deck#1]
> nw-shot@4.2.0 postinstall E:\nodejs\node_modules\@deck\app\node_modules\@deck\presenter\node_modules\bespoke-pdf\node_modules\bespoke-to-pdf\node_mo
dules\nw-shot
> install-nw
0.12.3 not in cache, fetching...
 http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win32-x64.zip
Error: http status code 404
    at Request._callback (E:\nodejs\node_modules\@deck\app\node_modules\@deck\presenter\node_modules\bespoke-pdf\node_modules\bespoke-to-pdf\node_modu
les\nw-shot\node_modules\fast-download\lib\FastDownload.js:32:45)
    at Request.self.callback (E:\nodejs\node_modules\@deck\app\node_modules\@deck\presenter\node_modules\bespoke-pdf\node_modules\bespoke-to-pdf\node_
modules\nw-shot\node_modules\fast-download\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (E:\nodejs\node_modules\@deck\app\node_modules\@deck\presenter\node_modules\bespoke-pdf\node_modules\bespoke-to-pdf\node_mo
dules\nw-shot\node_modules\fast-download\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (E:\nodejs\node_modules\@deck\app\node_modules\@deck\presenter\node_modules\bespoke-pdf\node_modules\bespoke-to-pdf
\node_modules\nw-shot\node_modules\fast-download\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\nodejs\\\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@deck/app"
npm ERR! node v0.10.38
npm ERR! npm  v2.9.1
npm ERR! path E:\nodejs\node_modules\@deck\app\node_modules\exec-sync\node_modules\ffi\node_modules\ref\package.json
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! Error: EPERM, rename 'E:\nodejs\node_modules\@deck\app\node_modules\exec-sync\node_modules\ffi\node_modules\ref\package.json'
npm ERR!  { [Error: EPERM, rename 'E:\nodejs\node_modules\@deck\app\node_modules\exec-sync\node_modules\ffi\node_modules\ref\package.json']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'E:\\nodejs\\node_modules\\@deck\\app\\node_modules\\exec-sync\\node_modules\\ffi\\node_modules\\ref\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     e:\GIT\isight\config_hp_v5\npm-debug.log
e:\GIT\isight\config_hp_v5>

**Comment by davidmarkclements** [comment]
this is no longer an issue
